language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
  include:
    - php: 7.2
      env: XDEBUG_OFF="yes"

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "5.3" ]; then composer require guzzlehttp/guzzle --no-update;  fi;'
  - if [[ $XDEBUG_OFF = yes ]]; then phpenv config-rm xdebug.ini; fi;

script:
  - make
  - make test-all

after_success:
  - make coveralls
